window:
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  decorations: none

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: PragmataPro Mono Liga
    style: Regular
  bold:
    family: PragmataPro Mono Liga
    style: Bold
  italic:
    family: PragmataPro Mono Liga
    style: Italic
  bold_italic:
    family: PragmataPro Mono Liga
    style: Bold Italic
  size: 14.0
  use_thin_strokes: true

background_opacity: 0.95

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true
