import:
  - ~/.config/alacritty/github-dark-default.yml

window:
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  decorations: none
  opacity: 1.0
  startup_mode: Maximized

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: PragmataPro
    style: Regular
  bold:
    family: PragmataPro
    style: Bold
  italic:
    family: PragmataPro
    style: Italic
  bold_italic:
    family: PragmataPro
    style: Bold Italic
  size: 12.0
  use_thin_strokes: true

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true
