import = ["~/.config/alacritty/catppuccin-mocha.toml"]
live_config_reload = true

[cursor]
style = "Block"
unfocused_hollow = true

[font]
size = 13.0

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Maximized"

[window.padding]
x = 5
y = 5
