window:
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  decorations: none

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: PragmataPro Mono Liga
    style: Regular
  bold:
    family: PragmataPro Mono Liga
    style: Bold
  italic:
    family: PragmataPro Mono Liga
    style: Italic
  bold_italic:
    family: PragmataPro Mono Liga
    style: Bold Italic
  size: 14.0
  use_thin_strokes: true

# LuciusDark
colors:
  primary:
    background: '#303030'
    foreground: '#d7d7d7'
  cursor:
    text:    '#303030'
    cursor:  '#87afd7'
  normal:
    black:   '#303030'
    red:     '#ff5f5f'
    green:   '#afd787'
    yellow:  '#d7d7af'
    blue:    '#87d7ff'
    magenta: '#d7afd7'
    cyan:    '#87d7af'
    white:   '#d7d7d7'
  bright:
    black:   '#303030'
    red:     '#ff5f5f'
    green:   '#afd787'
    yellow:  '#d7d7af'
    blue:    '#87d7ff'
    magenta: '#d7afd7'
    cyan:    '#87d7af'
    white:   '#d7d7d7'

background_opacity: 0.9

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true
