import:
  - ~/.config/alacritty/catppuccin-mocha.yml

window:
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  decorations: none
  startup_mode: Maximized

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: Berkeley Mono
    style: Regular
  bold:
    family: Berkeley Mono
    style: Bold
  italic:
    family: Berkeley Mono
    style: Italic
  bold_italic:
    family: Berkeley Mono
    style: Bold Italic
  size: 12.0

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true
