window:
  padding:
    x: 5
    y: 5
  dynamic_padding: true
  decorations: none

scrolling:
  history: 10000
  multiplier: 3

font:
  normal:
    family: PragmataPro Liga
    style: Regular
  bold:
    family: PragmataPro Liga
    style: Bold
  italic:
    family: PragmataPro Liga
    style: Italic
  bold_italic:
    family: PragmataPro Liga
    style: Bold Italic
  size: 12.0
  use_thin_strokes: true

# GitHub Dark
colors:
  primary:
    background: '0x24292e'
    foreground: '0xd1d5da'
  normal:
    black:   '0x24292e'
    red:     '0xf14c4c'
    green:   '0x23d18b'
    yellow:  '0xe2e210'
    blue:    '0x3b8eea'
    magenta: '0xbc3fbc'
    cyan:    '0x29b7da'
    white:   '0xd1d5da'
  bright:
    black:   '0x666666'
    red:     '0xf14c4c'
    green:   '0x23d18b'
    yellow:  '0xf5f543'
    blue:    '0x3b8eea'
    magenta: '0xd670d6'
    cyan:    '0x29b7da'
    white:   '0xd1d5da'
  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xf14c4c' }

# GitHub Light
colors:
  primary:
    background: '0xffffff'
    foreground: '0x586069'
  normal:
    black:   '0x697179'
    red:     '0xd03d3d'
    green:   '0x14ce14'
    yellow:  '0x949800'
    blue:    '0x0451a5'
    magenta: '0xbc05bc'
    cyan:    '0x0598bc'
    white:   '0x586069'
  bright:
    black:   '0x666666'
    red:     '0xcd3131'
    green:   '0x14ce14'
    yellow:  '0xb5ba00'
    blue:    '0x0451a5'
    magenta: '0xbc05bc'
    cyan:    '0x0598bc'
    white:   '0x586069'
  indexed_colors:
    - { index: 16, color: '0xd18616' }
    - { index: 17, color: '0xcd3131' }

cursor:
  style: Block
  unfocused_hollow: true

live_config_reload: true
